# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  - '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '*.nuspec'
    versioningScheme: 'byBuildNumber'
    toolPackage: true


steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your powershell commands here.
      
      Install-Module Pester -Force;
      Write-Host (Get-InstalledModule Pester).Version;
      Invoke-Pester -OutputFile Test-Unit.xml -OutputFormat NUnitXml
    workingDirectory: 'test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/TEST-*.xml'
    mergeTestResults: true

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

